### ISSUE TITLE
Не показывает значения счетчиков. 

### ISSUE THREAD

**Issue by baz88ka** [XNicON/hassio-atick#2]
Сенсоры счетчиков пишут "неизвестно". В логах ошибки. 

> Error adding entity sensor.atick_counter_a for domain sensor with platform deembot_atick

> Error adding entity sensor.atick_counter_b for domain sensor with platform deembot_atick

> Unexpected exception from <bound method ActiveBluetoothDataUpdateCoordinator._async_poll of <custom_components.deembot_atick.coordinator.ATickDataUpdateCoordinator object at 0x7fde766d90a0>>

> ValueError: Sensor sensor.atick_counter_a has device class 'water', state class 'total_increasing' unit 'm³' and suggested precision '2' thus indicating it has a numeric value; however, it has the non-numeric value: '<state sensor.atick_counter_a=unknown; state_class=total_increasing, unit_of_measurement=m³, device_class=water, icon=mdi:counter, friendly_name=aTick Counter A @ 2024-09-18T19:31:53.758958+08:00>' (<class 'homeassistant.core.State'>)

**Comment by baz88ka** [comment]
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.deembot_atick
Источник: helpers/debounce.py:137
интеграция: Deembot aTick BLE (документация, проблемы)
Первое сообщение: 19:37:51 (5 сообщений)
Последнее сообщение: 19:43:23

Unexpected exception from <bound method ActiveBluetoothDataUpdateCoordinator._async_poll of <custom_components.deembot_atick.coordinator.ATickDataUpdateCoordinator object at 0x7fde766d90a0>>
Unexpected exception from <bound method ActiveBluetoothDataUpdateCoordinator._async_poll of <custom_components.deembot_atick.coordinator.ATickDataUpdateCoordinator object at 0x7fdec4290920>>
Unexpected exception from <bound method ActiveBluetoothDataUpdateCoordinator._async_poll of <custom_components.deembot_atick.coordinator.ATickDataUpdateCoordinator object at 0x7fdea89b7410>>
Unexpected exception from <bound method ActiveBluetoothDataUpdateCoordinator._async_poll of <custom_components.deembot_atick.coordinator.ATickDataUpdateCoordinator object at 0x7fdea8b027b0>>
Unexpected exception from <bound method ActiveBluetoothDataUpdateCoordinator._async_poll of <custom_components.deembot_atick.coordinator.ATickDataUpdateCoordinator object at 0x7fde765ab9b0>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 662, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'State'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/active_update_coordinator.py", line 147, in _async_poll
    self._async_handle_bluetooth_poll()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/active_update_coordinator.py", line 152, in _async_handle_bluetooth_poll
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/passive_update_coordinator.py", line 60, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    raise ValueError(
ValueError: Sensor sensor.atick_counter_a has device class 'water', state class 'total_increasing' unit 'm³' and suggested precision '2' thus indicating it has a numeric value; however, it has the non-numeric value: '<state sensor.atick_counter_a=unavailable; restored=True, state_class=total_increasing, device_class=water, icon=mdi:counter, friendly_name=aTick  Counter A, supported_features=0, unit_of_measurement=m³ @ 2024-09-18T19:36:20.792372+08:00>' (<class 'homeassistant.core.State'>)

**Comment by baz88ka** [comment]
Регистратор: homeassistant.components.sensor
Источник: helpers/entity_platform.py:595
интеграция: Сенсор (документация, проблемы)
Первое сообщение: 19:36:17 (12 сообщений)
Последнее сообщение: 19:43:19

Error adding entity sensor.atick_counter_a for domain sensor with platform deembot_atick
Error adding entity sensor.atick_counter_b for domain sensor with platform deembot_atick
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 662, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'State'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    raise ValueError(
ValueError: Sensor sensor.atick_counter_a has device class 'water', state class 'total_increasing' unit 'm³' and suggested precision '2' thus indicating it has a numeric value; however, it has the non-numeric value: '<state sensor.atick_counter_a=unknown; state_class=total_increasing, unit_of_measurement=m³, device_class=water, icon=mdi:counter, friendly_name=aTick  Counter A @ 2024-09-18T19:31:53.758958+08:00>' (<class 'homeassistant.core.State'>)

**Comment by baz88ka** [comment]
Отвечу сам себе - нужно отключить пассивное сканирование в расширении Bluetooth

**Comment by XNicON** [comment]
Класс, надо бы в режим добавить!
